name: Scripts Location Test
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: which python3 && python3 .github/scripts/greet.py
      - run: which python && python .github/scripts/greet.py
